[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center"]
set = true

[templates.wallpaper-path]
input_path = './templates/wallpaper-path.conf'
output_path = '~/.config/hypr/wallpaper-path.conf'


[templates.hyprland]
input_path = './templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.waybar]
input_path = './templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.ohmyposh]
input_path = './templates/ohmyposh.json'
output_path = '~/.config/ohmyposh.json'

[templates.dunst]
input_path = './templates/dunst-colorsrc'
output_path = '~/.config/dunst/dunstrc'
post_hook = 'pkill -SIGUSR2 dunst'

[templates.wezterm]
input_path = './templates/wezterm-colors.lua'
output_path = '~/.config/wezterm/colors.lua'

[templates.zathura]
input_path = './templates/zathurarc'
output_path = '~/.config/zathura/zathurarc'
